### ISSUE TITLE
视频格式以及清晰度

### ISSUE THREAD

**Issue by lk-timeout** [whxru/DouyuTvGift#3]
1、格式虽然是MP4，但是有些播放器不能播放，显示损坏之类的，能播放也不能快进调时间。
2、清晰度，下载的视频应该是清晰度最低的，能否自适应调整下载最高清晰度视频。

**Comment by whxru** [comment]
@lk-timeout 对于不能播放、显示损坏、不能调时间的问题，请在视频录制完成后再尝试播放，我个人使用的播放器是PotPlayer。对于清晰度的问题，请在[DouyuTvGift.py](https://github.com/whxru/DouyuTvGift/blob/master/DouyuTvGift.py#L124)文件的124行中将`worst`改成你所需要的清晰度，可供选择的清晰度清参考streamlink的官方文档，目前有的清晰度是audio, high, low, medium, mobile (worst), source (best)

**Comment by lk-timeout** [comment]
经过修改代码，清晰度好了，很清楚。选择bset后，保存的视频，用爱奇艺，暴风之类的可以播放，可以调整进度条，快进时间。但是好像不能导入Adobe Premiere Pro CC编辑器，若有时间，可以研究一下，没有的话可以直接关闭这个issues，后续我用格式类工具转化提取一下下载视频，音频。最后谢谢大佬提供的开源软件。感谢。

**Comment by whxru** [comment]
@lk-timeout 目前尚不清楚这个问题能否复现，会考虑debug的，最近在这个repo的基础上做另外的东西，会对现在的代码进行一些修改，到时候可能就没有问题了。
